#!/bin/sh
# tb-bridge.sh — bring the Thunderbolt link up as a self-serving DHCP network.
#
# Loads the Thunderbolt driver, gives tbt1 a fixed 10.10.10.1/24, and runs
# dnsmasq as a DHCP-ONLY server on 10.10.10.0/24 so a Mac plugged into the
# Thunderbolt port auto-gets an address with zero Mac-side config (the M4 goal).
#
# Default driver is the in-tree ICM module (tb-build/thunderbolt.ko); override
# with NHI_KO=... (e.g. the standalone nhi-build/nhi.ko).  The two drivers claim
# the same NHI, so this unloads the other one first.
#
# Host-to-host link, NOT a gateway: it hands out NO default route and NO DNS, so
# the Mac keeps its own routing and just gains a 10.10.10.x address (SMB, ssh, iperf).
#
# Loading the module and bringing up the bridge are decoupled: the module is
# loaded (or found already loaded) and then the script waits for tbt1 to appear
# (it only shows up once the ThunderboltIP login completes, i.e. once the Mac is
# awake and plugged in).  "module already loaded" is never a reason to bail.
#
# Idempotent; safe to re-run.  Env overrides:
#   NHI_KO   driver module path        (default tb-build/thunderbolt.ko)
#   IF       interface                 (default tbt1)
#   WAIT     seconds to wait for tbt1  (default 60; 0 = wait forever)
#   WATCH    1 = stay resident and (re)configure on every link up/down
set -u

NHI_KO="${NHI_KO:-/home/swift/tb-build/thunderbolt.ko}"
IF="${IF:-tbt1}"
SELF_IP="10.10.10.1"
CIDR="24"
MASK="255.255.255.0"
DHCP_LO="10.10.10.10"
DHCP_HI="10.10.10.240"
LEASE="12h"
WAIT="${WAIT:-60}"
WATCH="${WATCH:-0}"
CONF="/usr/local/etc/dnsmasq.tbt.conf"
PIDF="/var/run/dnsmasq.tbt.pid"
LEASEF="/var/db/dnsmasq.tbt.leases"

log() { echo "[tb-bridge] $*"; }

# re-exec as root if needed
[ "$(id -u)" = 0 ] || exec doas "$0" "$@"

# ---------------------------------------------------------------------------
# 1. load the Thunderbolt driver, unloading a conflicting one first.
#    The in-tree ICM module 'thunderbolt' and the standalone 'nhi' both bind the
#    same NHI PCI function - only one may be loaded at a time.  This step always
#    leaves the requested module loaded and then falls through; it never exits
#    just because a module is present.
# ---------------------------------------------------------------------------
load_driver() {
	MOD=$(basename "$NHI_KO" .ko)
	for other in thunderbolt nhi; do
		[ "$other" = "$MOD" ] && continue
		if kldstat -q -n "$other" 2>/dev/null; then
			log "unloading conflicting driver: $other"
			kldunload "$other" || { log "could not unload $other"; return 1; }
		fi
	done
	if kldstat -q -n "$MOD" 2>/dev/null; then
		log "$MOD already loaded - continuing to bridge setup"
	else
		log "loading $MOD: $NHI_KO"
		kldload "$NHI_KO" || { log "kldload failed"; return 1; }
	fi
	return 0
}

# Wait for $IF to appear.  WAIT=0 waits forever; otherwise up to WAIT seconds.
# Returns 0 as soon as it exists, 1 on timeout (NOT fatal - the caller decides).
wait_for_if() {
	i=0
	while ! ifconfig "$IF" >/dev/null 2>&1; do
		i=$((i + 1))
		if [ "$WAIT" -ne 0 ] && [ "$i" -ge "$WAIT" ]; then
			return 1
		fi
		[ $((i % 10)) -eq 0 ] && log "still waiting for $IF (${i}s; needs the Mac awake + plugged in)"
		sleep 1
	done
	return 0
}

# Configure the self IP + DHCP on $IF.  Idempotent.
bringup_bridge() {
	ifconfig "$IF" inet "$SELF_IP/$CIDR" up 2>/dev/null
	log "$IF = $SELF_IP/$CIDR up"

	cat > "$CONF" <<CFG
# generated by tb-bridge.sh - DHCP-only on the Thunderbolt link ($IF)
port=0                         # no DNS service, DHCP only
interface=$IF
bind-interfaces                # bind $IF's address only; never touch LAN
except-interface=lo0
dhcp-authoritative
dhcp-range=$DHCP_LO,$DHCP_HI,$MASK,$LEASE
dhcp-option=3                  # empty router  -> no default route via TB
dhcp-option=6                  # empty DNS     -> leave the Mac's resolver alone
log-dhcp
CFG
	dnsmasq --test --conf-file="$CONF" || { log "dnsmasq config test FAILED"; return 1; }

	[ -f "$PIDF" ] && pkill -F "$PIDF" 2>/dev/null
	: > "$LEASEF" 2>/dev/null || true
	dnsmasq --conf-file="$CONF" --pid-file="$PIDF" --dhcp-leasefile="$LEASEF"
	log "dnsmasq DHCP up on $IF: pool $DHCP_LO-$DHCP_HI, self $SELF_IP"

	ifconfig "$IF" | sed -n '1,4p'
	sockstat -4 -l 2>/dev/null | grep dnsmasq || true
	log "ready - a Mac on the TB port will DHCP a 10.10.10.x address"
	return 0
}

# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------
load_driver || exit 1

if [ "$WATCH" = 1 ]; then
	# Resident mode: bring the bridge up on every link-up, tear the DHCP
	# server down on link-down, and wait for the next connect.  Run once,
	# survives the Mac sleeping / cable replugs.
	log "watch mode: waiting for $IF across connects (Ctrl-C to stop)"
	WAIT=0
	while :; do
		wait_for_if
		log "$IF present - configuring bridge"
		bringup_bridge || true
		# wait for the link to go away, then loop to reconfigure on return
		while ifconfig "$IF" >/dev/null 2>&1; do sleep 2; done
		log "$IF went away - stopping DHCP, waiting for reconnect"
		[ -f "$PIDF" ] && pkill -F "$PIDF" 2>/dev/null
	done
fi

# one-shot mode
if wait_for_if; then
	log "$IF present (carrier follows the TB session; DHCP can bind now)"
	bringup_bridge || exit 1
	exit 0
fi

# tbt1 did not come up in time.  The module IS loaded and armed; this is not a
# failure - the bridge will bind as soon as the Mac logs in.  Re-run this script
# then, or start it with WATCH=1 to have it wait and auto-configure.
log "$IF not up yet after ${WAIT}s - module loaded and ready."
log "  Re-run when the Mac is connected, or use: WATCH=1 $0"
exit 0
